export const supportedLocales = ["en-US", "ko-KR", "ja-JP"] as const;

export type AppLocale = (typeof supportedLocales)[number];

export function toAppLocale(value?: string | null): AppLocale {
  return value === "ko-KR" || value === "ja-JP" ? value : "en-US";
}

export const messages = {
  "ko-KR": {
    nav: { plans: "요금제", dashboard: "대시보드", support: "문의 게시판", characters: "캐릭터 설정", notices: "공지사항", viewNotices: "공지사항 보기" },
    footer: { links: [["/notice", "서비스 공지"], ["/privacy", "개인정보처리방침"], ["/terms", "서비스 이용약관"], ["/voice-policy", "음성 데이터 정책"], ["/billing", "요금제"]], details: ["상호명: Voice With AI", "대표자명: 김세훈, 강창묵 | 사업자등록번호: 준비 중", "이메일: help@example.com"] },
    dashboard: {
      title: "대시보드", signedIn: (name: string) => `${name} 계정으로 로그인되었습니다.`, discordTitle: "Discord 계정 연동", linked: (name: string) => `${name} 계정과 연결되었습니다.`, unlinked: "봇 사용 권한을 확인하려면 Discord 계정을 연결해야 합니다.", reconnect: "Discord 계정 다시 연결하기", connect: "Discord 계정 연결하기", invite: "봇 초대하기", overviewTitle: "내 활동 한눈에 보기", overviewDescription: "이번 달 사용량과 대화 준비 상태를 확인하세요.", viewPlans: "요금제 보기", currentPlan: "현재 요금제", managePlan: "요금제 관리", savedMemories: "저장된 기억", count: (value: number) => `${value}개`, manageMemories: "기억 관리", profile: "내 프로필", profileDescription: "닉네임, 언어, 기본 프로필 정보를 관리합니다.", voiceSettings: "음성 대화 설정", voiceSettingsDescription: "음성 처리 동의와 대화 응답 설정을 확인합니다.", support: "문의 게시판", supportDescription: "Discord 문의 게시판에서 도움을 받을 수 있습니다.", backHome: "처음으로 돌아가기",
    },
    onboarding: { trigger: "이용방법 다시 보기", eyebrow: "처음 오셨나요?", title: "Voice With AI 시작하기", description: "아래 2단계만 완료하면 Discord에서 AI 캐릭터와 음성 대화를 시작할 수 있어요.", note: "이 안내는 언제든 대시보드에서 다시 열 수 있습니다.", close: "닫기", linked: "연결 완료", connect: "Discord 계정 연동하기", invite: "봇 초대하기", inviteLocked: "계정 연동 후 가능", steps: [{ title: "Discord 계정 연동", description: "웹 계정과 Discord 계정을 연결해 봇 사용 권한을 확인하세요." }, { title: "봇 초대", description: "연동한 뒤 AI 캐릭터를 사용할 Discord 서버로 봇을 초대하세요." }] },
    characters: { title: "캐릭터 설정", description: "대화할 AI 캐릭터를 선택하고, 캐릭터와의 대화 방식을 설정하세요. 새 캐릭터는 준비되는 대로 이 목록에 추가됩니다.", selected: "선택됨", current: "현재 선택한 캐릭터", choose: "이 캐릭터 선택하기", saving: "저장 중...", comingSoon: "추가 예정", saved: "선택한 캐릭터가 저장되었습니다.", saveFailed: "캐릭터 선택을 저장하지 못했습니다. 다시 시도해주세요.", settings: "캐릭터 대화 설정", nickname: { title: "AI가 부를 이름", description: "캐릭터가 대화 중 나를 부를 이름을 설정하세요.", label: "호칭", placeholder: "예: 세훈", save: "이름 저장", saving: "저장 중...", saved: "AI가 부를 이름을 저장했습니다.", saveFailed: "이름을 저장하지 못했습니다. 2글자 이상 입력해주세요." }, cards: [{ title: "셀린", description: "다정하고 포근한 목소리로 함께 대화하는 AI 캐릭터" }, { title: "새 캐릭터 준비 중", description: "다음 AI 캐릭터가 이 자리에 추가됩니다." }, { title: "새 캐릭터 준비 중", description: "추가 캐릭터를 선택할 수 있도록 준비하고 있습니다." }] },
    assistantSettings: { title: "샐린 대화 설정", relationship: "관계 톤", friend: "친구", flirty: "썸", romantic: "연인", length: "답변 길이", short: "짧게", normal: "보통", long: "길게", style: "음성 스타일", expressive: "표현형", fast: "빠른 응답", barge: "끼어들기 방식", immediate: "말하면 즉시 중단", stop: "stop 명령일 때만 중단", memory: "장기기억 저장", sns: "SNS 말투", voice: "음성 응답", summary: "채팅 음성 요약", silent: "무음 알림", details: "상세 보기", save: "설정 저장", saving: "저장 중...", saved: "설정을 저장했습니다.", saveFailed: "설정을 저장하지 못했습니다.", descriptions: { memory_enabled: "호칭·취향을 기억해 다음 대화에 반영해요.", sns_tone_enabled: "짧고 편한 SNS 말투로 답해요.", voice_response_enabled: "음성 채널에서 답변을 읽어줘요.", voice_summary_enabled: "대화 핵심을 음성으로 요약해요. (준비 중)", silent_notification_enabled: "조용한 시간대의 알림을 조절해요." } },
    memory: { title: "기억 관리", intro: "캐릭터가 더 자연스럽게 대화할 수 있도록 저장된 장기기억을 확인하고 관리하세요.", count: "저장된 기억", items: (value: number) => `${value}개`, emptyTitle: "아직 저장된 기억이 없어요", emptyText: "셀린과 대화를 이어가면, 대화에 도움이 되는 내용을 장기기억으로 저장해 다음 만남에도 자연스럽게 이어갈 수 있어요.", character: "캐릭터 설정 보기", savedTitle: "저장된 기억", savedText: "중요한 기억은 고정하고, 원하지 않는 내용은 언제든 삭제할 수 있어요.", keeping: (value: number) => `${value}개 보관 중`, confidence: "신뢰도", pin: "고정", unpin: "고정 해제", remove: "삭제", clear: "전체 기억 삭제", tips: [["✦", "대화가 이어져요", "저장된 기억은 다음 대화에서 캐릭터가 맥락을 이해하는 데 도움을 줍니다."], ["📌", "중요한 기억 고정", "꼭 유지하고 싶은 내용은 고정해 한눈에 확인할 수 있어요."], ["⌁", "내가 직접 관리", "필요 없는 기억은 이 페이지에서 언제든 삭제할 수 있어요."]] },
    billing: { heading: "나에게 맞는 대화 플랜", intro: "대화 빈도와 이용 방식에 맞는 플랜을 골라보세요.", loginTitle: "로그인이 필요합니다", loginDescription: "요금제와 사용량을 확인하려면 먼저 로그인해주세요.", loginHint: "우측 상단 계정 아이콘에서 Google로 로그인을 선택해 주세요.", setupLabel: "DB 설정 필요", setupTitle: "결제 정보를 준비하고 있어요", setupDescription: "관리자가 결제 데이터를 설정하면 요금제를 이용할 수 있습니다.", monthly: "월간 구독", yearly: "연간 구독", twoMonthsFree: "2개월 무료", currentlyUsing: "현재 사용 중", popular: "추천", year: "년", month: "월", paymentSoon: "결제 기능 준비 중", selectAfterLogin: "로그인 후 플랜 선택하기", currentPlan: "현재 요금제", yearlyDiscount: "2개월 무료 적용", plans: [{ badge: "가볍게 시작", description: "좋아하는 캐릭터와 매일 조금씩 가까워져요.", features: ["월 텍스트 500회", "월 음성 30분", "기본 캐릭터 선택", "Discord 계정 연동"] }, { badge: "가장 인기", description: "더 오래, 더 깊게 대화하고 싶은 분을 위한 플랜이에요.", features: ["월 텍스트 3,000회", "월 음성 300분", "장기기억 기능 사용", "캐릭터 우선 응답"] }, { badge: "마음껏 대화", description: "캐릭터와의 시간을 가장 풍성하게 채워보세요.", features: ["월 텍스트 10,000회", "월 음성 1,000분", "장기기억 확장 사용", "새 기능 먼저 만나기"] }] },
    supportPage: { title: "문의 게시판", description: "서비스 이용 중 도움이 필요하거나 오류를 제보하고 싶으신가요? Discord 문의 게시판에서 운영팀에 메시지를 남겨주세요.", note: "버튼을 누르면 Discord 초대 페이지가 새 탭으로 열립니다.", action: "Discord 문의 게시판 열기" },
    credits: { label: "테스트 크레딧", remaining: "크레딧 남음", used: (value: string) => `이번 달 사용: ${value} 크레딧`, adding: "추가 중...", add: "테스트 크레딧 +1000", note: "임시 테스트용 충전이며 실제 결제는 발생하지 않습니다." },
  },
  "ja-JP": {
    nav: { plans: "料金プラン", dashboard: "ダッシュボード", support: "お問い合わせ", characters: "キャラクター設定", notices: "お知らせ", viewNotices: "お知らせを見る" },
    footer: { links: [["/notice", "お知らせ"], ["/privacy", "プライバシーポリシー"], ["/terms", "利用規約"], ["/voice-policy", "音声データポリシー"], ["/billing", "料金プラン"]], details: ["事業者名: Voice With AI", "代表者名: キム・セフン、カン・チャンムク | 事業者登録番号: 準備中", "メール: help@example.com"] },
    dashboard: {
      title: "ダッシュボード", signedIn: (name: string) => `${name} さんとしてログインしています。`, discordTitle: "Discord アカウント連携", linked: (name: string) => `${name} と連携済みです。`, unlinked: "ボットの利用権限を確認するには、Discord アカウントを連携してください。", reconnect: "Discord アカウントを再連携", connect: "Discord アカウントを連携", invite: "ボットを招待", overviewTitle: "アクティビティの概要", overviewDescription: "今月の利用状況と会話の準備状況を確認できます。", viewPlans: "料金プランを見る", currentPlan: "現在のプラン", managePlan: "プランを管理", savedMemories: "保存した記憶", count: (value: number) => `${value}件`, manageMemories: "記憶を管理", profile: "プロフィール", profileDescription: "ニックネーム、言語、基本プロフィールを管理します。", voiceSettings: "音声会話の設定", voiceSettingsDescription: "音声データの同意と会話応答の設定を確認します。", support: "お問い合わせ", supportDescription: "Discord の問い合わせ窓口からサポートを受けられます。", backHome: "ホームに戻る",
    },
    onboarding: { trigger: "使い方をもう一度見る", eyebrow: "はじめての方へ", title: "Voice With AI をはじめよう", description: "次の2ステップを完了すると、Discord で AI キャラクターとの音声会話を始められます。", note: "このガイドはいつでもダッシュボードから開けます。", close: "閉じる", linked: "連携済み", connect: "Discord アカウントを連携", invite: "ボットを招待", inviteLocked: "連携後に利用可能", steps: [{ title: "Discord アカウントを連携", description: "Web アカウントと Discord を連携して、ボットの利用権限を確認します。" }, { title: "ボットを招待", description: "連携後、AI キャラクターを使う Discord サーバーにボットを招待します。" }] },
    characters: { title: "キャラクター設定", description: "会話したい AI キャラクターを選び、会話方法を設定できます。新しいキャラクターは準備ができ次第追加されます。", selected: "選択中", current: "現在選択中のキャラクター", choose: "このキャラクターを選ぶ", saving: "保存中...", comingSoon: "準備中", saved: "選択したキャラクターを保存しました。", saveFailed: "キャラクターの選択を保存できませんでした。もう一度お試しください。", settings: "キャラクター会話設定", nickname: { title: "AIが呼ぶ名前", description: "キャラクターが会話中にあなたを呼ぶ名前を設定できます。", label: "呼び名", placeholder: "例：セフン", save: "名前を保存", saving: "保存中...", saved: "AIが呼ぶ名前を保存しました。", saveFailed: "名前を保存できませんでした。2文字以上入力してください。" }, cards: [{ title: "セリン", description: "やさしく温かな声で寄り添う AI キャラクター" }, { title: "新しいキャラクターを準備中", description: "次の AI キャラクターがここに追加されます。" }, { title: "新しいキャラクターを準備中", description: "選択できる新しいキャラクターを準備しています。" }] },
    assistantSettings: { title: "セリンとの会話設定", relationship: "関係性", friend: "友達", flirty: "いい感じ", romantic: "恋人", length: "返答の長さ", short: "短め", normal: "普通", long: "長め", style: "音声スタイル", expressive: "表現豊か", fast: "素早い応答", barge: "割り込み方法", immediate: "話し始めたらすぐ停止", stop: "停止コマンドのときだけ停止", memory: "長期記憶を保存", sns: "SNS風の話し方", voice: "音声で応答", summary: "会話の音声要約", silent: "通知を控える時間", details: "詳細", save: "設定を保存", saving: "保存中...", saved: "設定を保存しました。", saveFailed: "設定を保存できませんでした。", descriptions: { memory_enabled: "呼び方や好みを記憶して、次の会話に反映します。", sns_tone_enabled: "短く親しみやすい SNS 風の話し方で返答します。", voice_response_enabled: "音声チャンネルで返答を読み上げます。", voice_summary_enabled: "会話の要点を音声で要約します。（準備中）", silent_notification_enabled: "静かな時間帯の通知を調整します。" } },
    memory: { title: "記憶管理", intro: "キャラクターとの会話がより自然になるよう、保存した長期記憶を確認・管理できます。", count: "保存した記憶", items: (value: number) => `${value}件`, emptyTitle: "まだ保存された記憶はありません", emptyText: "セリンとの会話を続けると、役立つ内容を長期記憶として保存し、次の会話にも自然に活かせます。", character: "キャラクター設定を見る", savedTitle: "保存した記憶", savedText: "大切な記憶は固定し、不要な内容はいつでも削除できます。", keeping: (value: number) => `${value}件を保存中`, confidence: "信頼度", pin: "固定", unpin: "固定を解除", remove: "削除", clear: "すべての記憶を削除", tips: [["✦", "会話がつながる", "保存した記憶は、次の会話でキャラクターが文脈を理解する助けになります。"], ["📌", "大切な記憶を固定", "残しておきたい内容を固定すると、いつでも確認しやすくなります。"], ["⌁", "自分で管理できる", "不要になった記憶は、このページからいつでも削除できます。"]] },
    billing: { heading: "あなたに合う会話プラン", intro: "会話の頻度や使い方に合ったプランを選べます。", loginTitle: "ログインが必要です", loginDescription: "料金プランと利用状況を確認するには、先にログインしてください。", loginHint: "右上のアカウントアイコンから Google ログインを選択してください。", setupLabel: "請求設定が必要です", setupTitle: "決済情報を準備しています", setupDescription: "管理者が決済データを設定すると、料金プランを利用できます。", monthly: "月額", yearly: "年額", twoMonthsFree: "2か月無料", currentlyUsing: "利用中", popular: "人気", year: "年", month: "月", paymentSoon: "決済機能を準備中", selectAfterLogin: "ログインしてプランを選ぶ", currentPlan: "現在のプラン", yearlyDiscount: "2か月無料を適用", plans: [{ badge: "気軽に始める", description: "好きなキャラクターと毎日少しずつ仲良くなれるプランです。", features: ["月500回のテキストメッセージ", "月30分の音声会話", "基本キャラクターの選択", "Discord アカウント連携"] }, { badge: "一番人気", description: "毎日もっと長く、深く会話したい方のためのプランです。", features: ["月3,000回のテキストメッセージ", "月300分の音声会話", "長期記憶機能", "キャラクターの優先応答"] }, { badge: "たっぷり会話", description: "キャラクターとの時間をより豊かに楽しめるプランです。", features: ["月10,000回のテキストメッセージ", "月1,000分の音声会話", "拡張長期記憶", "新機能の先行利用"] }] },
    supportPage: { title: "お問い合わせ", description: "サービスの利用で困ったことや不具合の報告がある場合は、Discord の問い合わせ窓口から運営チームにご連絡ください。", note: "ボタンを押すと、Discord の招待ページが新しいタブで開きます。", action: "Discord の問い合わせ窓口を開く" },
    credits: { label: "テストクレジット", remaining: "クレジット残高", used: (value: string) => `今月の利用: ${value} クレジット`, adding: "追加中...", add: "テストクレジット +1,000", note: "テスト用の一時チャージです。実際の決済は発生しません。" },
  },
  "en-US": {
    nav: { plans: "Plans", dashboard: "Dashboard", support: "Support", characters: "Characters", notices: "Notices", viewNotices: "View notices" },
    footer: { links: [["/notice", "Notices"], ["/privacy", "Privacy Policy"], ["/terms", "Terms of Service"], ["/voice-policy", "Voice Data Policy"], ["/billing", "Plans"]], details: ["Business name: Voice With AI", "Representatives: Kim Se-hoon, Kang Chang-mook | Business registration: Coming soon", "Email: help@example.com"] },
    dashboard: {
      title: "Dashboard", signedIn: (name: string) => `Signed in as ${name}.`, discordTitle: "Discord account connection", linked: (name: string) => `Connected to ${name}.`, unlinked: "Connect your Discord account to verify bot access.", reconnect: "Reconnect Discord account", connect: "Connect Discord account", invite: "Invite the bot", overviewTitle: "Your activity at a glance", overviewDescription: "Check this month’s usage and your conversation setup.", viewPlans: "View plans", currentPlan: "Current plan", managePlan: "Manage plan", savedMemories: "Saved memories", count: (value: number) => `${value} saved`, manageMemories: "Manage memories", profile: "My profile", profileDescription: "Manage your nickname, language, and basic profile information.", voiceSettings: "Voice conversation settings", voiceSettingsDescription: "Review voice processing consent and conversation response settings.", support: "Support", supportDescription: "Get help through the Discord support board.", backHome: "Back to home",
    },
    onboarding: { trigger: "View getting started guide", eyebrow: "New here?", title: "Get started with Voice With AI", description: "Complete these two steps to start voice conversations with AI characters on Discord.", note: "You can reopen this guide anytime from the dashboard.", close: "Close", linked: "Connected", connect: "Connect Discord account", invite: "Invite the bot", inviteLocked: "Connect your account first", steps: [{ title: "Connect Discord", description: "Connect your web and Discord accounts to verify bot access." }, { title: "Invite the bot", description: "After connecting, invite the bot to the Discord server where you want to use it." }] },
    characters: { title: "Character settings", description: "Choose the AI character you want to talk with and set your conversation preferences. New characters will appear here when they are ready.", selected: "Selected", current: "Current character", choose: "Choose this character", saving: "Saving...", comingSoon: "Coming soon", saved: "Your selected character has been saved.", saveFailed: "We could not save your selection. Please try again.", settings: "Character conversation settings", nickname: { title: "Name your AI uses", description: "Choose the name your character will use when speaking to you.", label: "Preferred name", placeholder: "For example, Sehoon", save: "Save name", saving: "Saving...", saved: "Your preferred name has been saved.", saveFailed: "We could not save your name. Enter at least 2 characters." }, cards: [{ title: "Seline", description: "A warm AI character who keeps you company." }, { title: "New character coming soon", description: "The next AI character will be added here." }, { title: "New character coming soon", description: "Another selectable character is being prepared." }] },
    assistantSettings: { title: "Seline conversation settings", relationship: "Relationship tone", friend: "Friend", flirty: "Flirty", romantic: "Romantic", length: "Response length", short: "Short", normal: "Normal", long: "Long", style: "Voice style", expressive: "Expressive", fast: "Fast", barge: "Barge-in mode", immediate: "Stop when you start speaking", stop: "Stop only on a stop command", memory: "Save long-term memories", sns: "Social tone", voice: "Voice responses", summary: "Read chat summaries aloud", silent: "Quiet-time notifications", details: "Details", save: "Save settings", saving: "Saving...", saved: "Settings saved.", saveFailed: "We could not save your settings.", descriptions: { memory_enabled: "Saves useful preferences such as names and interests to make future conversations more personal.", sns_tone_enabled: "Uses a more relaxed, short social-message style when it fits the conversation.", voice_response_enabled: "Lets Seline speak replies in a voice channel. Turn it off for text-only replies.", voice_summary_enabled: "Reads a short spoken summary of the conversation. This feature is still being prepared.", silent_notification_enabled: "Controls helpful notifications during quiet periods and limits how often they appear." } },
    memory: { title: "Memory", intro: "Review and manage long-term memories to make character conversations feel more natural.", count: "Saved memories", items: (value: number) => `${value} items`, emptyTitle: "No memories saved yet", emptyText: "As you continue conversations with Seline, helpful details can be saved as long-term memories for more natural future chats.", character: "View character settings", savedTitle: "Saved memories", savedText: "Pin important memories and delete anything you no longer want saved.", keeping: (value: number) => `${value} saved`, confidence: "Confidence", pin: "Pin", unpin: "Unpin", remove: "Delete", clear: "Delete all memories", tips: [["✦", "Conversations continue", "Saved memories help your character understand the context in future conversations."], ["📌", "Pin important memories", "Pin the details you want to keep visible and easy to review."], ["⌁", "You stay in control", "You can remove memories you no longer need at any time."]] },
    billing: { heading: "A plan that fits your conversations", intro: "Choose the plan that fits how often you talk.", loginTitle: "Login required", loginDescription: "Please log in to view your subscription and usage.", loginHint: "Use the account icon in the top-right corner to continue with Google.", setupLabel: "Billing setup required", setupTitle: "Billing is being prepared", setupDescription: "The plans will be available after billing data is configured.", monthly: "Monthly", yearly: "Yearly", twoMonthsFree: "2 months free", currentlyUsing: "Currently using", popular: "Popular", year: "year", month: "month", paymentSoon: "Payment coming soon", selectAfterLogin: "Sign in to choose this plan", currentPlan: "Current plan", yearlyDiscount: "2 months free applied", plans: [{ badge: "A gentle start", description: "A lovely way to get a little closer to your favorite character every day.", features: ["500 text messages / month", "30 voice minutes / month", "Basic character selection", "Discord account connection"] }, { badge: "Most popular", description: "Made for anyone who wants longer, deeper conversations every day.", features: ["3,000 text messages / month", "300 voice minutes / month", "Long-term memory", "Priority character responses"] }, { badge: "Talk freely", description: "Fill your time with the richest, most personal character experience.", features: ["10,000 text messages / month", "1,000 voice minutes / month", "Expanded long-term memory", "Early access to new features"] }] },
    supportPage: { title: "Support board", description: "Need help using the service or want to report a problem? Leave a message for our team in the Discord support board.", note: "The button opens the Discord invitation page in a new tab.", action: "Open Discord support board" },
    credits: { label: "Test credits", remaining: "credits left", used: (value: string) => `Used this month: ${value}`, adding: "Adding...", add: "+1,000 test credits", note: "Temporary test top-up. No payment is charged." },
  },
} as const;

export function getMessages(locale?: string | null) {
  return messages[toAppLocale(locale)];
}
